/**
 * QRMS Migration Engine - Firestore to PostgreSQL Collection Mapping
 * 
 * Strict 1:1 mapping definitions preserving document IDs, tenant contexts,
 * organization links, typed columns, and foreign key relationships.
 */

import { CollectionMigrationConfig } from '../core/migrationTypes';

export const COLLECTION_MAPPINGS: Record<string, CollectionMigrationConfig> = {
  // ---------------------------------------------------------------------------
  // Tier 1: Core Independent Master Tables
  // ---------------------------------------------------------------------------
  organizations: {
    firestoreCollection: 'organizations',
    postgresTable: 'organizations',
    primaryKey: 'id',
    order: 1,
    description: 'جمعيات التحفيظ والمقرات الرئيسية (Master Organizations)',
    dependencies: [],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'name', postgresColumn: 'name', type: 'string', required: true },
      { firestoreField: 'code', postgresColumn: 'code', type: 'string' },
      { firestoreField: 'licenseNumber', postgresColumn: 'license_number', type: 'string' },
      { firestoreField: 'logoUrl', postgresColumn: 'logo_url', type: 'string' },
      { firestoreField: 'tenantIds', postgresColumn: 'tenant_ids', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'isActive', postgresColumn: 'is_active', type: 'boolean', defaultValue: true },
      { firestoreField: 'rolePermissionsOverrides', postgresColumn: 'role_permissions_overrides', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'description', postgresColumn: 'description', type: 'string' },
      { firestoreField: 'city', postgresColumn: 'city', type: 'string' },
      { firestoreField: 'region', postgresColumn: 'region', type: 'string' },
      { firestoreField: 'contactPhone', postgresColumn: 'contact_phone', type: 'string' },
      { firestoreField: 'contactEmail', postgresColumn: 'contact_email', type: 'string' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  educational_stages: {
    firestoreCollection: 'educational_stages',
    postgresTable: 'stages',
    primaryKey: 'id',
    order: 2,
    description: 'المراحل التعليمية (Educational Stages)',
    dependencies: [],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'code', postgresColumn: 'code', type: 'string', required: true },
      { firestoreField: 'name', postgresColumn: 'name', type: 'string', required: true },
      { firestoreField: 'subtitle', postgresColumn: 'subtitle', type: 'string' },
      { firestoreField: 'ageRange', postgresColumn: 'age_range', type: 'string' },
      { firestoreField: 'targetGrades', postgresColumn: 'target_grades', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'curriculumFocus', postgresColumn: 'curriculum_focus', type: 'string' },
      { firestoreField: 'defaultTargetSurah', postgresColumn: 'default_target_surah', type: 'string', defaultValue: 'الغاشية' },
      { firestoreField: 'accentColor', postgresColumn: 'accent_color', type: 'string', defaultValue: 'emerald' },
      { firestoreField: 'iconName', postgresColumn: 'icon_name', type: 'string', defaultValue: 'Sparkles' },
      { firestoreField: 'order', postgresColumn: 'display_order', type: 'number', defaultValue: 1 },
      { firestoreField: 'isActive', postgresColumn: 'is_active', type: 'boolean', defaultValue: true },
      { firestoreField: 'rolePermissionsOverrides', postgresColumn: 'role_permissions_overrides', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'traits', postgresColumn: 'traits', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'outcomeSummary', postgresColumn: 'outcome_summary', type: 'string' },
      { firestoreField: 'targetQuranAmount', postgresColumn: 'target_quran_amount', type: 'string' },
      { firestoreField: 'logoUrl', postgresColumn: 'logo_url', type: 'string' },
      { firestoreField: 'isLogoActive', postgresColumn: 'is_logo_active', type: 'boolean', defaultValue: true },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  quran_stage_configs: {
    firestoreCollection: 'quran_stage_configs',
    postgresTable: 'quran_stage_configs',
    primaryKey: 'id',
    order: 3,
    description: 'خطط وإعدادات القرآن للمراحل (Stage Quran Configs)',
    dependencies: [],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'name', postgresColumn: 'name', type: 'string', required: true },
      { firestoreField: 'code', postgresColumn: 'code', type: 'string', required: true },
      { firestoreField: 'description', postgresColumn: 'description', type: 'string' },
      { firestoreField: 'targetGrades', postgresColumn: 'target_grades', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'dailyPaceDescription', postgresColumn: 'daily_pace_description', type: 'string' },
      { firestoreField: 'memorization', postgresColumn: 'memorization', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'revision', postgresColumn: 'revision', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'consolidationDays', postgresColumn: 'consolidation_days', type: 'number', defaultValue: 3 },
      { firestoreField: 'schedule', postgresColumn: 'schedule', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'defaultTermWeeks', postgresColumn: 'default_term_weeks', type: 'number', defaultValue: 12 },
      { firestoreField: 'isActive', postgresColumn: 'is_active', type: 'boolean', defaultValue: true },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  academic_years: {
    firestoreCollection: 'academic_years',
    postgresTable: 'academic_years',
    primaryKey: 'id',
    order: 4,
    description: 'إعدادات العام الدراسي والأسابيع (Academic Years)',
    dependencies: [],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'name', postgresColumn: 'name', type: 'string', required: true },
      { firestoreField: 'semester', postgresColumn: 'semester', type: 'string', required: true },
      { firestoreField: 'currentTerm', postgresColumn: 'current_term', type: 'string' },
      { firestoreField: 'academicYear', postgresColumn: 'academic_year', type: 'string' },
      { firestoreField: 'startDate', postgresColumn: 'start_date', type: 'date', required: true },
      { firestoreField: 'endDate', postgresColumn: 'end_date', type: 'date', required: true },
      { firestoreField: 'holidays', postgresColumn: 'holidays', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'operationalStartWeek', postgresColumn: 'operational_start_week', type: 'number', defaultValue: 3 },
      { firestoreField: 'operationalEndWeek', postgresColumn: 'operational_end_week', type: 'number', defaultValue: 14 },
      { firestoreField: 'totalWeeks', postgresColumn: 'total_weeks', type: 'number', defaultValue: 12 },
      { firestoreField: 'currentWeek', postgresColumn: 'current_week', type: 'number', defaultValue: 5 },
      { firestoreField: 'manualWeekOverride', postgresColumn: 'manual_week_override', type: 'boolean', defaultValue: false },
      { firestoreField: 'daysPerWeek', postgresColumn: 'days_per_week', type: 'number', defaultValue: 4 },
      { firestoreField: 'spellingPassingThreshold', postgresColumn: 'spelling_passing_threshold', type: 'number', defaultValue: 85.0 },
      { firestoreField: 'gradeTargets', postgresColumn: 'grade_targets', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  spelling_lessons: {
    firestoreCollection: 'spelling_lessons',
    postgresTable: 'spelling_lessons',
    primaryKey: 'id',
    order: 5,
    description: 'بنك دروس الهجاء القرآني (Spelling Lessons)',
    dependencies: [],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'lessonNumber', postgresColumn: 'lesson_number', type: 'number', required: true },
      { firestoreField: 'title', postgresColumn: 'title', type: 'string', required: true },
      { firestoreField: 'skill', postgresColumn: 'skill', type: 'string' },
      { firestoreField: 'description', postgresColumn: 'description', type: 'string' },
      { firestoreField: 'expectedWeek', postgresColumn: 'expected_week', type: 'number' },
      { firestoreField: 'targetGrade', postgresColumn: 'target_grade', type: 'string' },
      { firestoreField: 'passingThreshold', postgresColumn: 'passing_threshold', type: 'number', defaultValue: 85.0 },
      { firestoreField: 'passingScore', postgresColumn: 'passing_score', type: 'number', defaultValue: 85.0 },
      { firestoreField: 'order', postgresColumn: 'display_order', type: 'number', defaultValue: 1 },
      { firestoreField: 'isActive', postgresColumn: 'is_active', type: 'boolean', defaultValue: true },
      { firestoreField: 'coreSkills', postgresColumn: 'core_skills', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'subLessons', postgresColumn: 'sub_lessons', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  // ---------------------------------------------------------------------------
  // Tier 2: Tenants (Depend on Organizations)
  // ---------------------------------------------------------------------------
  tenants: {
    firestoreCollection: 'tenants',
    postgresTable: 'tenants',
    primaryKey: 'id',
    organizationKey: 'organization_id',
    order: 6,
    description: 'المجمعات والمراكز القرآنية (Tenants / Mosque Complexes)',
    dependencies: ['organizations'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'slug', postgresColumn: 'slug', type: 'string', required: true },
      { firestoreField: 'name', postgresColumn: 'name', type: 'string', required: true },
      { firestoreField: 'organizationId', postgresColumn: 'organization_id', type: 'string', isForeignKey: true, foreignKeyTable: 'organizations' },
      { firestoreField: 'description', postgresColumn: 'description', type: 'string' },
      { firestoreField: 'city', postgresColumn: 'city', type: 'string', defaultValue: 'الرياض' },
      { firestoreField: 'district', postgresColumn: 'district', type: 'string', defaultValue: 'المركز الرئيسي' },
      { firestoreField: 'region', postgresColumn: 'region', type: 'string' },
      { firestoreField: 'address', postgresColumn: 'address', type: 'string' },
      { firestoreField: 'supervisorName', postgresColumn: 'supervisor_name', type: 'string', defaultValue: 'المشرف العام' },
      { firestoreField: 'contactPhone', postgresColumn: 'contact_phone', type: 'string', defaultValue: '0500000000' },
      { firestoreField: 'email', postgresColumn: 'email', type: 'string' },
      { firestoreField: 'whatsappNumber', postgresColumn: 'whatsapp_number', type: 'string' },
      { firestoreField: 'logoUrl', postgresColumn: 'logo_url', type: 'string' },
      { firestoreField: 'stageLogoUrl', postgresColumn: 'stage_logo_url', type: 'string' },
      { firestoreField: 'targetSurahDefault', postgresColumn: 'target_surah_default', type: 'string', defaultValue: 'الغاشية' },
      { firestoreField: 'referenceOutcome', postgresColumn: 'reference_outcome', type: 'string' },
      { firestoreField: 'supportedStages', postgresColumn: 'supported_stages', type: 'jsonb', defaultValue: ['baraem', 'ashbal'] },
      { firestoreField: 'isActive', postgresColumn: 'is_active', type: 'boolean', defaultValue: true },
      { firestoreField: 'rolePermissionsOverrides', postgresColumn: 'role_permissions_overrides', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'customDomain', postgresColumn: 'custom_domain', type: 'string' },
      { firestoreField: 'tenantType', postgresColumn: 'tenant_type', type: 'string', defaultValue: 'production' },
      { firestoreField: 'showOnPublicDirectory', postgresColumn: 'show_on_public_directory', type: 'boolean', defaultValue: true },
      { firestoreField: 'subscription', postgresColumn: 'subscription', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'modulesConfig', postgresColumn: 'modules_config', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'attendanceConfig', postgresColumn: 'attendance_config', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'prayerConfig', postgresColumn: 'prayer_config', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'admissionsConfig', postgresColumn: 'admissions_config', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'reportsConfig', postgresColumn: 'reports_config', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'whatsappConfig', postgresColumn: 'whatsapp_config', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  // ---------------------------------------------------------------------------
  // Tier 3: Users & Track Definitions (Depend on Tenants, Stages, Organizations)
  // ---------------------------------------------------------------------------
  platform_users: {
    firestoreCollection: 'platform_users',
    postgresTable: 'users',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    organizationKey: 'organization_id',
    order: 7,
    description: 'المستخدمون والكوادر الإدارية والتعليمية (Users & Staff)',
    dependencies: ['tenants', 'organizations', 'stages'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'organizationId', postgresColumn: 'organization_id', type: 'string', isForeignKey: true, foreignKeyTable: 'organizations' },
      { firestoreField: 'name', postgresColumn: 'name', type: 'string', required: true },
      { firestoreField: 'fullName', postgresColumn: 'full_name', type: 'string' },
      { firestoreField: 'phone', postgresColumn: 'phone', type: 'string', required: true },
      { firestoreField: 'email', postgresColumn: 'email', type: 'string' },
      { firestoreField: 'nationalId', postgresColumn: 'national_id', type: 'string' },
      { firestoreField: 'loginIdentifier', postgresColumn: 'login_identifier', type: 'string' },
      { firestoreField: 'passwordHash', postgresColumn: 'password_hash', type: 'string' },
      { firestoreField: 'role', postgresColumn: 'role', type: 'string', required: true },
      { firestoreField: 'staffRole', postgresColumn: 'staff_role', type: 'string' },
      { firestoreField: 'halaqahId', postgresColumn: 'halaqah_id', type: 'string' },
      { firestoreField: 'stageId', postgresColumn: 'stage_id', type: 'string', isForeignKey: true, foreignKeyTable: 'stages' },
      { firestoreField: 'studentId', postgresColumn: 'student_id', type: 'string' },
      { firestoreField: 'teacherId', postgresColumn: 'teacher_id', type: 'string' },
      { firestoreField: 'studentIds', postgresColumn: 'student_ids', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'supervisionMode', postgresColumn: 'supervision_mode', type: 'string', defaultValue: 'full_access' },
      { firestoreField: 'isActive', postgresColumn: 'is_active', type: 'boolean', defaultValue: true },
      { firestoreField: 'mustChangePassword', postgresColumn: 'must_change_password', type: 'boolean', defaultValue: false },
      { firestoreField: 'permissionMode', postgresColumn: 'permission_mode', type: 'string', defaultValue: 'role_defaults' },
      { firestoreField: 'rolePermissionsOverrides', postgresColumn: 'role_permissions_overrides', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'customPermissions', postgresColumn: 'custom_permissions', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'temporaryCustomPermissions', postgresColumn: 'temporary_custom_permissions', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'supervisorScope', postgresColumn: 'supervisor_scope', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'assignedStageIds', postgresColumn: 'assigned_stage_ids', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'assignedHalaqahIds', postgresColumn: 'assigned_halaqah_ids', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'isAllHalaqahs', postgresColumn: 'is_all_halaqahs', type: 'boolean', defaultValue: false },
      { firestoreField: 'delegations', postgresColumn: 'delegations', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'isArchived', postgresColumn: 'is_archived', type: 'boolean', defaultValue: false },
      { firestoreField: 'teacherArchived', postgresColumn: 'teacher_archived', type: 'boolean', defaultValue: false },
      { firestoreField: 'supervisorArchived', postgresColumn: 'supervisor_archived', type: 'boolean', defaultValue: false },
      { firestoreField: 'archiveType', postgresColumn: 'archive_type', type: 'string' },
      { firestoreField: 'archivedAt', postgresColumn: 'archived_at', type: 'timestamp' },
      { firestoreField: 'archivedBy', postgresColumn: 'archived_by', type: 'string' },
      { firestoreField: 'archiveReason', postgresColumn: 'archive_reason', type: 'string' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  track_definitions: {
    firestoreCollection: 'track_definitions',
    postgresTable: 'track_definitions',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 8,
    description: 'المسارات التخصصية القرآنية (Track Definitions)',
    dependencies: ['tenants'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'code', postgresColumn: 'code', type: 'string', required: true },
      { firestoreField: 'name', postgresColumn: 'name', type: 'string', required: true },
      { firestoreField: 'shortName', postgresColumn: 'short_name', type: 'string', required: true },
      { firestoreField: 'description', postgresColumn: 'description', type: 'string' },
      { firestoreField: 'icon', postgresColumn: 'icon', type: 'string', defaultValue: 'BookOpen' },
      { firestoreField: 'colorScheme', postgresColumn: 'color_scheme', type: 'string', defaultValue: 'emerald' },
      { firestoreField: 'isActive', postgresColumn: 'is_active', type: 'boolean', defaultValue: true },
      { firestoreField: 'rolePermissionsOverrides', postgresColumn: 'role_permissions_overrides', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'order', postgresColumn: 'display_order', type: 'number', defaultValue: 1 },
      { firestoreField: 'nominationConfig', postgresColumn: 'nomination_config', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  // ---------------------------------------------------------------------------
  // Tier 4: Halaqahs (Depend on Tenants, Stages, Users/Teachers)
  // ---------------------------------------------------------------------------
  halaqahs: {
    firestoreCollection: 'halaqahs',
    postgresTable: 'halaqahs',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 9,
    description: 'الحلقات القرآنية (Halaqahs)',
    dependencies: ['tenants', 'stages', 'users'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'stageId', postgresColumn: 'stage_id', type: 'string', isForeignKey: true, foreignKeyTable: 'stages' },
      { firestoreField: 'name', postgresColumn: 'name', type: 'string', required: true },
      { firestoreField: 'teacherId', postgresColumn: 'teacher_id', type: 'string', isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'teacherName', postgresColumn: 'teacher_name', type: 'string', required: true },
      { firestoreField: 'teacherPhone', postgresColumn: 'teacher_phone', type: 'string' },
      { firestoreField: 'location', postgresColumn: 'location', type: 'string', defaultValue: 'المسجد' },
      { firestoreField: 'daysPerWeek', postgresColumn: 'days_per_week', type: 'number', defaultValue: 4 },
      { firestoreField: 'grade', postgresColumn: 'grade', type: 'string' },
      { firestoreField: 'targetSurah', postgresColumn: 'target_surah', type: 'string', defaultValue: 'الغاشية' },
      { firestoreField: 'assistantTeachers', postgresColumn: 'assistant_teachers', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'onlineConfig', postgresColumn: 'online_config', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'weeklySchedule', postgresColumn: 'weekly_schedule', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'defaultTimeType', postgresColumn: 'default_time_type', type: 'string', defaultValue: 'fixed' },
      { firestoreField: 'defaultStartTime', postgresColumn: 'default_start_time', type: 'string' },
      { firestoreField: 'defaultEndTime', postgresColumn: 'default_end_time', type: 'string' },
      { firestoreField: 'defaultStartPrayerOffset', postgresColumn: 'default_start_prayer_offset', type: 'jsonb' },
      { firestoreField: 'defaultEndPrayerOffset', postgresColumn: 'default_end_prayer_offset', type: 'jsonb' },
      { firestoreField: 'activeTrackIds', postgresColumn: 'active_track_ids', type: 'jsonb', defaultValue: ['track_quran', 'track_spelling', 'track_virtues'] },
      { firestoreField: 'rolePermissionsOverrides', postgresColumn: 'role_permissions_overrides', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'isActive', postgresColumn: 'is_active', type: 'boolean', defaultValue: true },
      { firestoreField: 'isArchived', postgresColumn: 'is_archived', type: 'boolean', defaultValue: false },
      { firestoreField: 'archivedAt', postgresColumn: 'archived_at', type: 'timestamp' },
      { firestoreField: 'archivedBy', postgresColumn: 'archived_by', type: 'string' },
      { firestoreField: 'archiveReason', postgresColumn: 'archive_reason', type: 'string' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  // ---------------------------------------------------------------------------
  // Tier 5: Students (Depend on Tenants, Stages, Halaqahs, Users, Spelling Lessons)
  // ---------------------------------------------------------------------------
  students: {
    firestoreCollection: 'students',
    postgresTable: 'students',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 10,
    description: 'ملفات وسجلات الطلاب (Students)',
    dependencies: ['tenants', 'stages', 'halaqahs', 'users', 'spelling_lessons'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'stageId', postgresColumn: 'stage_id', type: 'string', isForeignKey: true, foreignKeyTable: 'stages' },
      { firestoreField: 'halaqahId', postgresColumn: 'halaqah_id', type: 'string', isForeignKey: true, foreignKeyTable: 'halaqahs' },
      { firestoreField: 'teacherId', postgresColumn: 'teacher_id', type: 'string', isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'fullName', postgresColumn: 'full_name', type: 'string', required: true },
      { firestoreField: 'nationalId', postgresColumn: 'national_id', type: 'string' },
      { firestoreField: 'grade', postgresColumn: 'grade', type: 'string', required: true },
      { firestoreField: 'halaqahName', postgresColumn: 'halaqah_name', type: 'string' },
      { firestoreField: 'teacherName', postgresColumn: 'teacher_name', type: 'string' },
      { firestoreField: 'teacherPhone', postgresColumn: 'teacher_phone', type: 'string' },
      { firestoreField: 'parentName', postgresColumn: 'parent_name', type: 'string' },
      { firestoreField: 'parentPhone', postgresColumn: 'parent_phone', type: 'string', required: true },
      { firestoreField: 'phone', postgresColumn: 'phone', type: 'string' },
      { firestoreField: 'motherPhone', postgresColumn: 'mother_phone', type: 'string' },
      { firestoreField: 'guardianRelationship', postgresColumn: 'guardian_relationship', type: 'string' },
      { firestoreField: 'otherContactPhone', postgresColumn: 'other_contact_phone', type: 'string' },
      { firestoreField: 'minimumTargetSurah', postgresColumn: 'minimum_target_surah', type: 'string', defaultValue: 'الغاشية' },
      { firestoreField: 'personalTargetSurah', postgresColumn: 'personal_target_surah', type: 'string' },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'on_track' },
      { firestoreField: 'currentSpellingLessonId', postgresColumn: 'current_spelling_lesson_id', type: 'string', isForeignKey: true, foreignKeyTable: 'spelling_lessons' },
      { firestoreField: 'currentSpellingScore', postgresColumn: 'current_spelling_score', type: 'number', defaultValue: 0 },
      { firestoreField: 'currentSurah', postgresColumn: 'current_surah', type: 'string', defaultValue: 'الناس' },
      { firestoreField: 'currentAyah', postgresColumn: 'current_ayah', type: 'number', defaultValue: 1 },
      { firestoreField: 'avatarUrl', postgresColumn: 'avatar_url', type: 'string' },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'username', postgresColumn: 'username', type: 'string' },
      { firestoreField: 'activeQuranPlanId', postgresColumn: 'active_quran_plan_id', type: 'string' },
      { firestoreField: 'quranPlan', postgresColumn: 'quran_plan', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'termHistories', postgresColumn: 'term_histories', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'attendanceStreak', postgresColumn: 'attendance_streak', type: 'number', defaultValue: 0 },
      { firestoreField: 'registrationType', postgresColumn: 'registration_type', type: 'string' },
      { firestoreField: 'registrationTypeLabel', postgresColumn: 'registration_type_label', type: 'string' },
      { firestoreField: 'previouslyRegistered', postgresColumn: 'previously_registered', type: 'string' },
      { firestoreField: 'isActive', postgresColumn: 'is_active', type: 'boolean', defaultValue: true },
      { firestoreField: 'isArchived', postgresColumn: 'is_archived', type: 'boolean', defaultValue: false },
      { firestoreField: 'archivedAt', postgresColumn: 'archived_at', type: 'timestamp' },
      { firestoreField: 'archiveReason', postgresColumn: 'archive_reason', type: 'string' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  // ---------------------------------------------------------------------------
  // Tier 6: Student Dependents (Quran Plans, Daily Records, Financial, Badges, Remedial)
  // ---------------------------------------------------------------------------
  quran_plans: {
    firestoreCollection: 'quran_plans',
    postgresTable: 'quran_plans',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 11,
    description: 'خطط القرآن الفردية للطلاب (Student Quran Plans)',
    dependencies: ['tenants', 'students', 'stages'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'studentId', postgresColumn: 'student_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'students' },
      { firestoreField: 'stageId', postgresColumn: 'stage_id', type: 'string', isForeignKey: true, foreignKeyTable: 'stages' },
      { firestoreField: 'planName', postgresColumn: 'plan_name', type: 'string' },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'active' },
      { firestoreField: 'scope', postgresColumn: 'scope', type: 'string', defaultValue: 'semester' },
      { firestoreField: 'direction', postgresColumn: 'direction', type: 'string', defaultValue: 'backward' },
      { firestoreField: 'unitType', postgresColumn: 'unit_type', type: 'string', defaultValue: 'ayah' },
      { firestoreField: 'dailyAmount', postgresColumn: 'daily_amount', type: 'number' },
      { firestoreField: 'planData', postgresColumn: 'plan_data', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  daily_records: {
    firestoreCollection: 'daily_records',
    postgresTable: 'daily_session_records',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 12,
    description: 'سجلات الحفظ والهجاء والحضور اليومية (Daily Session Records)',
    dependencies: ['tenants', 'students', 'halaqahs', 'users'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'studentId', postgresColumn: 'student_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'students' },
      { firestoreField: 'teacherId', postgresColumn: 'teacher_id', type: 'string', isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'halaqahId', postgresColumn: 'halaqah_id', type: 'string', isForeignKey: true, foreignKeyTable: 'halaqahs' },
      { firestoreField: 'date', postgresColumn: 'date', type: 'date', required: true },
      { firestoreField: 'dayOfWeek', postgresColumn: 'day_of_week', type: 'string' },
      { firestoreField: 'weekNumber', postgresColumn: 'week_number', type: 'number', required: true },
      { firestoreField: 'attendance', postgresColumn: 'attendance', type: 'string', defaultValue: 'present' },
      { firestoreField: 'teacherRemarks', postgresColumn: 'teacher_remarks', type: 'string' },
      { firestoreField: 'spellingDrillMinutes', postgresColumn: 'spelling_drill_minutes', type: 'number', defaultValue: 10 },
      { firestoreField: 'spellingProgress', postgresColumn: 'spelling_progress', type: 'jsonb' },
      { firestoreField: 'spelling', postgresColumn: 'spelling', type: 'jsonb' },
      { firestoreField: 'memorization', postgresColumn: 'memorization', type: 'jsonb' },
      { firestoreField: 'revision', postgresColumn: 'revision', type: 'jsonb' },
      { firestoreField: 'customTracks', postgresColumn: 'custom_tracks', type: 'jsonb' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  educational_plan: {
    firestoreCollection: 'educational_plan',
    postgresTable: 'educational_plan_weeks',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 13,
    description: 'الخطة التربوية والقيمية الأسبوعية (Educational Plan Weeks)',
    dependencies: ['tenants', 'stages'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'stageId', postgresColumn: 'stage_id', type: 'string', isForeignKey: true, foreignKeyTable: 'stages' },
      { firestoreField: 'targetStageIds', postgresColumn: 'target_stage_ids', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'weekNumber', postgresColumn: 'week_number', type: 'number', required: true },
      { firestoreField: 'startDate', postgresColumn: 'start_date', type: 'date', required: true },
      { firestoreField: 'endDate', postgresColumn: 'end_date', type: 'date', required: true },
      { firestoreField: 'dayDates', postgresColumn: 'day_dates', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'weekType', postgresColumn: 'week_type', type: 'string', defaultValue: 'normal' },
      { firestoreField: 'specialEventTitle', postgresColumn: 'special_event_title', type: 'string' },
      { firestoreField: 'domain', postgresColumn: 'domain', type: 'string' },
      { firestoreField: 'domainLabel', postgresColumn: 'domain_label', type: 'string' },
      { firestoreField: 'valueTitle', postgresColumn: 'value_title', type: 'string' },
      { firestoreField: 'motto', postgresColumn: 'motto', type: 'string', defaultValue: 'قيمنا حياتنا' },
      { firestoreField: 'educationalGoal', postgresColumn: 'educational_goal', type: 'string', defaultValue: 'تعزيز القيم التربوية' },
      { firestoreField: 'goalTopic', postgresColumn: 'goal_topic', type: 'string' },
      { firestoreField: 'goalPresenter', postgresColumn: 'goal_presenter', type: 'string' },
      { firestoreField: 'goalLocation', postgresColumn: 'goal_location', type: 'string' },
      { firestoreField: 'activity', postgresColumn: 'activity', type: 'string', defaultValue: 'نشاط تربوي' },
      { firestoreField: 'activityPresenter', postgresColumn: 'activity_presenter', type: 'string' },
      { firestoreField: 'activityLocation', postgresColumn: 'activity_location', type: 'string' },
      { firestoreField: 'responsiblePerson', postgresColumn: 'responsible_person', type: 'string', defaultValue: 'المشرف' },
      { firestoreField: 'quranicProgram', postgresColumn: 'quranic_program', type: 'string' },
      { firestoreField: 'overallProjectBudget', postgresColumn: 'overall_project_budget', type: 'number', defaultValue: 0 },
      { firestoreField: 'budget', postgresColumn: 'budget', type: 'number', defaultValue: 0 },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'valuesList', postgresColumn: 'values_list', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'executionStatus', postgresColumn: 'execution_status', type: 'string', defaultValue: 'planned' },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'scheduled' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  seasonal_programs: {
    firestoreCollection: 'seasonal_programs',
    postgresTable: 'seasonal_programs',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 14,
    description: 'البرامج الموسمية (Seasonal Programs)',
    dependencies: ['tenants', 'users'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'title', postgresColumn: 'title', type: 'string', required: true },
      { firestoreField: 'name', postgresColumn: 'name', type: 'string' },
      { firestoreField: 'code', postgresColumn: 'code', type: 'string' },
      { firestoreField: 'type', postgresColumn: 'type', type: 'string', required: true },
      { firestoreField: 'season', postgresColumn: 'season', type: 'string' },
      { firestoreField: 'startDate', postgresColumn: 'start_date', type: 'date', required: true },
      { firestoreField: 'endDate', postgresColumn: 'end_date', type: 'date', required: true },
      { firestoreField: 'targetStageIds', postgresColumn: 'target_stage_ids', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'targetAudience', postgresColumn: 'target_audience', type: 'string' },
      { firestoreField: 'location', postgresColumn: 'location', type: 'string' },
      { firestoreField: 'maxCapacity', postgresColumn: 'max_capacity', type: 'number' },
      { firestoreField: 'supervisorId', postgresColumn: 'supervisor_id', type: 'string', isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'supervisorName', postgresColumn: 'supervisor_name', type: 'string' },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'active' },
      { firestoreField: 'budget', postgresColumn: 'budget', type: 'number', defaultValue: 0 },
      { firestoreField: 'description', postgresColumn: 'description', type: 'string' },
      { firestoreField: 'goals', postgresColumn: 'goals', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'enrolledStudentIds', postgresColumn: 'enrolled_student_ids', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  seasonal_activities: {
    firestoreCollection: 'seasonal_activities',
    postgresTable: 'seasonal_activities',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 15,
    description: 'أنشطة البرامج الموسمية (Seasonal Activities)',
    dependencies: ['seasonal_programs', 'tenants', 'users'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'programId', postgresColumn: 'program_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'seasonal_programs' },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'title', postgresColumn: 'title', type: 'string', required: true },
      { firestoreField: 'description', postgresColumn: 'description', type: 'string' },
      { firestoreField: 'activityType', postgresColumn: 'activity_type', type: 'string' },
      { firestoreField: 'category', postgresColumn: 'category', type: 'string' },
      { firestoreField: 'dayOfWeek', postgresColumn: 'day_of_week', type: 'string' },
      { firestoreField: 'date', postgresColumn: 'date', type: 'date' },
      { firestoreField: 'timeSlot', postgresColumn: 'time_slot', type: 'string' },
      { firestoreField: 'responsibleName', postgresColumn: 'responsible_name', type: 'string' },
      { firestoreField: 'supervisorName', postgresColumn: 'supervisor_name', type: 'string' },
      { firestoreField: 'supervisorId', postgresColumn: 'supervisor_id', type: 'string', isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'location', postgresColumn: 'location', type: 'string' },
      { firestoreField: 'points', postgresColumn: 'points', type: 'number', defaultValue: 0 },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'planned' },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  seasonal_participations: {
    firestoreCollection: 'seasonal_participations',
    postgresTable: 'seasonal_participations',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 16,
    description: 'مشاركات الطلاب في الأنشطة الموسمية (Seasonal Participations)',
    dependencies: ['seasonal_programs', 'seasonal_activities', 'tenants', 'students'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'programId', postgresColumn: 'program_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'seasonal_programs' },
      { firestoreField: 'activityId', postgresColumn: 'activity_id', type: 'string', isForeignKey: true, foreignKeyTable: 'seasonal_activities' },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'studentId', postgresColumn: 'student_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'students' },
      { firestoreField: 'studentName', postgresColumn: 'student_name', type: 'string' },
      { firestoreField: 'originalHalaqahId', postgresColumn: 'original_halaqah_id', type: 'string' },
      { firestoreField: 'originalHalaqahName', postgresColumn: 'original_halaqah_name', type: 'string' },
      { firestoreField: 'attendanceStatus', postgresColumn: 'attendance_status', type: 'string', required: true },
      { firestoreField: 'participationLevel', postgresColumn: 'participation_level', type: 'string' },
      { firestoreField: 'seasonalPointsEarned', postgresColumn: 'seasonal_points_earned', type: 'number', defaultValue: 0 },
      { firestoreField: 'pointsEarned', postgresColumn: 'points_earned', type: 'number', defaultValue: 0 },
      { firestoreField: 'achievementNote', postgresColumn: 'achievement_note', type: 'string' },
      { firestoreField: 'recordedBy', postgresColumn: 'recorded_by', type: 'string' },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'recordedAt', postgresColumn: 'recorded_at', type: 'timestamp' },
    ],
  },

  financial_records: {
    firestoreCollection: 'financial_records',
    postgresTable: 'student_financial_records',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 17,
    description: 'السجلات المالية والرسوم للطلاب (Student Financial Records)',
    dependencies: ['tenants', 'students'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'studentId', postgresColumn: 'student_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'students' },
      { firestoreField: 'studentName', postgresColumn: 'student_name', type: 'string', required: true },
      { firestoreField: 'academicYear', postgresColumn: 'academic_year', type: 'string', required: true },
      { firestoreField: 'baseTuition', postgresColumn: 'base_tuition', type: 'number', defaultValue: 0 },
      { firestoreField: 'discountAmount', postgresColumn: 'discount_amount', type: 'number', defaultValue: 0 },
      { firestoreField: 'discountReason', postgresColumn: 'discount_reason', type: 'string' },
      { firestoreField: 'scholarshipAmount', postgresColumn: 'scholarship_amount', type: 'number', defaultValue: 0 },
      { firestoreField: 'isExempt', postgresColumn: 'is_exempt', type: 'boolean', defaultValue: false },
      { firestoreField: 'exemptionReason', postgresColumn: 'exemption_reason', type: 'string' },
      { firestoreField: 'paidAmount', postgresColumn: 'paid_amount', type: 'number', defaultValue: 0 },
      { firestoreField: 'remainingAmount', postgresColumn: 'remaining_amount', type: 'number', defaultValue: 0 },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'unpaid' },
      { firestoreField: 'payments', postgresColumn: 'payments', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  revenues: {
    firestoreCollection: 'revenues',
    postgresTable: 'finance_revenues',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 18,
    description: 'إيرادات وسندات القبض (Finance Revenues)',
    dependencies: ['tenants'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'sourceName', postgresColumn: 'source_name', type: 'string', required: true },
      { firestoreField: 'amount', postgresColumn: 'amount', type: 'number', required: true },
      { firestoreField: 'date', postgresColumn: 'date', type: 'date', required: true },
      { firestoreField: 'donorOrSource', postgresColumn: 'donor_or_source', type: 'string' },
      { firestoreField: 'paymentMethod', postgresColumn: 'payment_method', type: 'string', required: true },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'createdBy', postgresColumn: 'created_by', type: 'string' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
    ],
  },

  expenses: {
    firestoreCollection: 'expenses',
    postgresTable: 'finance_expenses',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 19,
    description: 'المصروفات وسندات الصرف (Finance Expenses)',
    dependencies: ['tenants'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'category', postgresColumn: 'category', type: 'string', required: true },
      { firestoreField: 'description', postgresColumn: 'description', type: 'string', required: true },
      { firestoreField: 'amount', postgresColumn: 'amount', type: 'number', required: true },
      { firestoreField: 'taxAmount', postgresColumn: 'tax_amount', type: 'number', defaultValue: 0 },
      { firestoreField: 'totalAmount', postgresColumn: 'total_amount', type: 'number', required: true },
      { firestoreField: 'date', postgresColumn: 'date', type: 'date', required: true },
      { firestoreField: 'beneficiary', postgresColumn: 'beneficiary', type: 'string', required: true },
      { firestoreField: 'paymentMethod', postgresColumn: 'payment_method', type: 'string', required: true },
      { firestoreField: 'programName', postgresColumn: 'program_name', type: 'string' },
      { firestoreField: 'invoiceNumber', postgresColumn: 'invoice_number', type: 'string' },
      { firestoreField: 'attachmentUrl', postgresColumn: 'attachment_url', type: 'string' },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'createdBy', postgresColumn: 'created_by', type: 'string' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
    ],
  },

  custodies: {
    firestoreCollection: 'custodies',
    postgresTable: 'finance_custodies',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 20,
    description: 'العهد المالية وإغلاقها (Finance Custodies)',
    dependencies: ['tenants', 'users'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'holderId', postgresColumn: 'holder_id', type: 'string', isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'holderName', postgresColumn: 'holder_name', type: 'string', required: true },
      { firestoreField: 'purpose', postgresColumn: 'purpose', type: 'string', required: true },
      { firestoreField: 'originalAmount', postgresColumn: 'original_amount', type: 'number', required: true },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'draft' },
      { firestoreField: 'disbursedAt', postgresColumn: 'disbursed_at', type: 'timestamp' },
      { firestoreField: 'settledAt', postgresColumn: 'settled_at', type: 'timestamp' },
      { firestoreField: 'closedAt', postgresColumn: 'closed_at', type: 'timestamp' },
      { firestoreField: 'reviewedBy', postgresColumn: 'reviewed_by', type: 'string' },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'createdBy', postgresColumn: 'created_by', type: 'string' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
    ],
  },

  budget_requests: {
    firestoreCollection: 'budget_requests',
    postgresTable: 'finance_budget_requests',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 21,
    description: 'طلبات الميزانية والبرامج (Finance Budget Requests)',
    dependencies: ['tenants', 'users'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'requesterId', postgresColumn: 'requester_id', type: 'string', isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'requesterName', postgresColumn: 'requester_name', type: 'string', required: true },
      { firestoreField: 'programName', postgresColumn: 'program_name', type: 'string', required: true },
      { firestoreField: 'estimatedAmount', postgresColumn: 'estimated_amount', type: 'number', required: true },
      { firestoreField: 'justification', postgresColumn: 'justification', type: 'string', required: true },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'pending' },
      { firestoreField: 'reviewedBy', postgresColumn: 'reviewed_by', type: 'string' },
      { firestoreField: 'reviewedAt', postgresColumn: 'reviewed_at', type: 'timestamp' },
      { firestoreField: 'reviewNotes', postgresColumn: 'review_notes', type: 'string' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
    ],
  },

  finance_settings: {
    firestoreCollection: 'finance_settings',
    postgresTable: 'finance_settings',
    primaryKey: 'tenant_id',
    tenantKey: 'tenant_id',
    order: 22,
    description: 'إعدادات وسياسات المالية للمستأجر (Finance Settings)',
    dependencies: ['tenants'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'tenant_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'revenueSources', postgresColumn: 'revenue_sources', type: 'jsonb', defaultValue: ['رسوم الطلاب', 'تبرعات', 'دعم', 'أوقاف', 'أخرى'] },
      { firestoreField: 'expenseCategories', postgresColumn: 'expense_categories', type: 'jsonb', defaultValue: ['تشغيلي', 'رواتب ومكافآت', 'برامج وأنشطة', 'قرطاسية', 'جوائز وهدايا', 'أخرى'] },
      { firestoreField: 'paymentMethods', postgresColumn: 'payment_methods', type: 'jsonb', defaultValue: ['نقدي', 'تحويل بنكي', 'شبكة', 'أخرى'] },
      { firestoreField: 'tuitionConfigs', postgresColumn: 'tuition_configs', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'defaultTuitionAmount', postgresColumn: 'default_tuition_amount', type: 'number', defaultValue: 0 },
      { firestoreField: 'bankAccounts', postgresColumn: 'bank_accounts', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'financialPolicies', postgresColumn: 'financial_policies', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  registration_requests: {
    firestoreCollection: 'registration_requests',
    postgresTable: 'registration_requests',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 23,
    description: 'طلبات التسجيل والقبول (Registration Requests)',
    dependencies: ['tenants', 'stages', 'halaqahs', 'users', 'students'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'studentName', postgresColumn: 'student_name', type: 'string', required: true },
      { firestoreField: 'nationalId', postgresColumn: 'national_id', type: 'string' },
      { firestoreField: 'parentName', postgresColumn: 'parent_name', type: 'string', required: true },
      { firestoreField: 'parentPhone', postgresColumn: 'parent_phone', type: 'string', required: true },
      { firestoreField: 'motherPhone', postgresColumn: 'mother_phone', type: 'string' },
      { firestoreField: 'guardianRelationship', postgresColumn: 'guardian_relationship', type: 'string' },
      { firestoreField: 'otherContactPhone', postgresColumn: 'other_contact_phone', type: 'string' },
      { firestoreField: 'birthDate', postgresColumn: 'birth_date', type: 'date' },
      { firestoreField: 'grade', postgresColumn: 'grade', type: 'string', required: true },
      { firestoreField: 'registrationType', postgresColumn: 'registration_type', type: 'string' },
      { firestoreField: 'registrationTypeLabel', postgresColumn: 'registration_type_label', type: 'string' },
      { firestoreField: 'tuitionFeeAmount', postgresColumn: 'tuition_fee_amount', type: 'number' },
      { firestoreField: 'feePledgeAccepted', postgresColumn: 'fee_pledge_accepted', type: 'boolean', defaultValue: false },
      { firestoreField: 'previouslyRegistered', postgresColumn: 'previously_registered', type: 'string' },
      { firestoreField: 'desiredStageId', postgresColumn: 'desired_stage_id', type: 'string', isForeignKey: true, foreignKeyTable: 'stages' },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'pending' },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'interviewNotes', postgresColumn: 'interview_notes', type: 'string' },
      { firestoreField: 'interviewScore', postgresColumn: 'interview_score', type: 'number' },
      { firestoreField: 'financialDecisionNotes', postgresColumn: 'financial_decision_notes', type: 'string' },
      { firestoreField: 'assignedHalaqahId', postgresColumn: 'assigned_halaqah_id', type: 'string', isForeignKey: true, foreignKeyTable: 'halaqahs' },
      { firestoreField: 'assignedTeacherId', postgresColumn: 'assigned_teacher_id', type: 'string', isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'enrolledStudentId', postgresColumn: 'enrolled_student_id', type: 'string', isForeignKey: true, foreignKeyTable: 'students' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  track_nominations: {
    firestoreCollection: 'track_nominations',
    postgresTable: 'track_nominations',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 24,
    description: 'ترشيحات واختبارات المسارات (Track Nominations)',
    dependencies: ['tenants', 'track_definitions', 'students', 'halaqahs', 'users'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'trackId', postgresColumn: 'track_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'track_definitions' },
      { firestoreField: 'trackName', postgresColumn: 'track_name', type: 'string' },
      { firestoreField: 'studentId', postgresColumn: 'student_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'students' },
      { firestoreField: 'studentName', postgresColumn: 'student_name', type: 'string', required: true },
      { firestoreField: 'halaqahId', postgresColumn: 'halaqah_id', type: 'string', isForeignKey: true, foreignKeyTable: 'halaqahs' },
      { firestoreField: 'halaqahName', postgresColumn: 'halaqah_name', type: 'string' },
      { firestoreField: 'teacherId', postgresColumn: 'teacher_id', type: 'string', isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'teacherName', postgresColumn: 'teacher_name', type: 'string' },
      { firestoreField: 'targetBranchOrLevel', postgresColumn: 'target_branch_or_level', type: 'string', required: true },
      { firestoreField: 'targetBranchSnapshot', postgresColumn: 'target_branch_snapshot', type: 'string' },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'submitted' },
      { firestoreField: 'nominationCardNumber', postgresColumn: 'nomination_card_number', type: 'string' },
      { firestoreField: 'internalExam', postgresColumn: 'internal_exam', type: 'jsonb' },
      { firestoreField: 'supervisorApproval', postgresColumn: 'supervisor_approval', type: 'jsonb' },
      { firestoreField: 'associationExam', postgresColumn: 'association_exam', type: 'jsonb' },
      { firestoreField: 'teacherRecommendation', postgresColumn: 'teacher_recommendation', type: 'string' },
      { firestoreField: 'teacherNotes', postgresColumn: 'teacher_notes', type: 'string' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  association_nominations: {
    firestoreCollection: 'association_nominations',
    postgresTable: 'association_nominations',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 25,
    description: 'ترشيحات اختبارات الجمعية (Association Nominations)',
    dependencies: ['tenants', 'students', 'halaqahs', 'users'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'studentId', postgresColumn: 'student_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'students' },
      { firestoreField: 'studentName', postgresColumn: 'student_name', type: 'string', required: true },
      { firestoreField: 'halaqahId', postgresColumn: 'halaqah_id', type: 'string', isForeignKey: true, foreignKeyTable: 'halaqahs' },
      { firestoreField: 'halaqahName', postgresColumn: 'halaqah_name', type: 'string' },
      { firestoreField: 'teacherId', postgresColumn: 'teacher_id', type: 'string', isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'teacherName', postgresColumn: 'teacher_name', type: 'string' },
      { firestoreField: 'nominationType', postgresColumn: 'nomination_type', type: 'string', required: true },
      { firestoreField: 'targetTitle', postgresColumn: 'target_title', type: 'string', required: true },
      { firestoreField: 'internalExamScore', postgresColumn: 'internal_exam_score', type: 'number', defaultValue: 0 },
      { firestoreField: 'teacherRecommendation', postgresColumn: 'teacher_recommendation', type: 'string' },
      { firestoreField: 'teacherNotes', postgresColumn: 'teacher_notes', type: 'string' },
      { firestoreField: 'supervisorStatus', postgresColumn: 'supervisor_status', type: 'string', defaultValue: 'pending' },
      { firestoreField: 'supervisorNotes', postgresColumn: 'supervisor_notes', type: 'string' },
      { firestoreField: 'nominationCardNumber', postgresColumn: 'nomination_card_number', type: 'string' },
      { firestoreField: 'approvedAt', postgresColumn: 'approved_at', type: 'timestamp' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  badges: {
    firestoreCollection: 'badges',
    postgresTable: 'student_badges',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 26,
    description: 'أوسمة وتحفيز الطلاب (Student Badges)',
    dependencies: ['tenants', 'students'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'badgeType', postgresColumn: 'badge_type', type: 'string', required: true },
      { firestoreField: 'studentId', postgresColumn: 'student_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'students' },
      { firestoreField: 'studentName', postgresColumn: 'student_name', type: 'string', required: true },
      { firestoreField: 'awardedAt', postgresColumn: 'awarded_at', type: 'date', required: true },
      { firestoreField: 'awardedBy', postgresColumn: 'awarded_by', type: 'string', required: true },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'isAutomatic', postgresColumn: 'is_automatic', type: 'boolean', defaultValue: false },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
    ],
  },

  remedial_plans: {
    firestoreCollection: 'remedial_plans',
    postgresTable: 'remedial_plans',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 27,
    description: 'الخطط العلاجية للطلاب (Remedial Action Plans)',
    dependencies: ['tenants', 'students', 'halaqahs', 'users'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'studentId', postgresColumn: 'student_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'students' },
      { firestoreField: 'studentName', postgresColumn: 'student_name', type: 'string', required: true },
      { firestoreField: 'halaqahId', postgresColumn: 'halaqah_id', type: 'string', isForeignKey: true, foreignKeyTable: 'halaqahs' },
      { firestoreField: 'teacherId', postgresColumn: 'teacher_id', type: 'string', isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'riskLevel', postgresColumn: 'risk_level', type: 'string', required: true },
      { firestoreField: 'category', postgresColumn: 'category', type: 'string', required: true },
      { firestoreField: 'title', postgresColumn: 'title', type: 'string', required: true },
      { firestoreField: 'diagnosticSummary', postgresColumn: 'diagnostic_summary', type: 'string', required: true },
      { firestoreField: 'recommendedAction', postgresColumn: 'recommended_action', type: 'string', required: true },
      { firestoreField: 'parentGuidance', postgresColumn: 'parent_guidance', type: 'string' },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'active' },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  meetings: {
    firestoreCollection: 'meetings',
    postgresTable: 'meetings',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 28,
    description: 'محاضر الاجتماعات والقرارات (Official Meetings)',
    dependencies: ['tenants', 'users'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'title', postgresColumn: 'title', type: 'string', required: true },
      { firestoreField: 'meetingNumber', postgresColumn: 'meeting_number', type: 'string' },
      { firestoreField: 'category', postgresColumn: 'category', type: 'string', defaultValue: 'general' },
      { firestoreField: 'date', postgresColumn: 'date', type: 'date', required: true },
      { firestoreField: 'startTime', postgresColumn: 'start_time', type: 'string', required: true },
      { firestoreField: 'endTime', postgresColumn: 'end_time', type: 'string' },
      { firestoreField: 'locationType', postgresColumn: 'location_type', type: 'string', defaultValue: 'in_person' },
      { firestoreField: 'location', postgresColumn: 'location', type: 'string' },
      { firestoreField: 'meetingUrl', postgresColumn: 'meeting_url', type: 'string' },
      { firestoreField: 'description', postgresColumn: 'description', type: 'string' },
      { firestoreField: 'objectives', postgresColumn: 'objectives', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'agenda', postgresColumn: 'agenda', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'attendees', postgresColumn: 'attendees', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'discussions', postgresColumn: 'discussions', type: 'string' },
      { firestoreField: 'decisions', postgresColumn: 'decisions', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'recommendations', postgresColumn: 'recommendations', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'postponedItems', postgresColumn: 'postponed_items', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'scheduled' },
      { firestoreField: 'cancellationReason', postgresColumn: 'cancellation_reason', type: 'string' },
      { firestoreField: 'createdBy', postgresColumn: 'created_by', type: 'string', isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'createdByName', postgresColumn: 'created_by_name', type: 'string', defaultValue: 'المشرف' },
      { firestoreField: 'createdByRole', postgresColumn: 'created_by_role', type: 'string', defaultValue: 'supervisor' },
      { firestoreField: 'completedAt', postgresColumn: 'completed_at', type: 'timestamp' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  staff_attendance: {
    firestoreCollection: 'staff_attendance',
    postgresTable: 'staff_attendance',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 29,
    description: 'حضور وانصراف الكادر التعليمي والإداري (Staff Attendance)',
    dependencies: ['tenants', 'users'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'userId', postgresColumn: 'user_id', type: 'string', required: true, isForeignKey: true, foreignKeyTable: 'users' },
      { firestoreField: 'userName', postgresColumn: 'user_name', type: 'string', required: true },
      { firestoreField: 'userRole', postgresColumn: 'user_role', type: 'string', required: true },
      { firestoreField: 'date', postgresColumn: 'date', type: 'date', required: true },
      { firestoreField: 'timestamp', postgresColumn: 'timestamp', type: 'timestamp', required: true },
      { firestoreField: 'isRegularDay', postgresColumn: 'is_regular_day', type: 'boolean', defaultValue: true },
      { firestoreField: 'reason', postgresColumn: 'reason', type: 'string' },
      { firestoreField: 'method', postgresColumn: 'method', type: 'string', defaultValue: 'geo' },
      { firestoreField: 'locationData', postgresColumn: 'location_data', type: 'jsonb' },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
    ],
  },

  prayer_times: {
    firestoreCollection: 'prayer_times',
    postgresTable: 'prayer_times',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 30,
    description: 'مواقيت الصلاة السنوية (Prayer Times Cache)',
    dependencies: ['tenants'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'year', postgresColumn: 'year', type: 'number', required: true },
      { firestoreField: 'latitude', postgresColumn: 'latitude', type: 'number', required: true },
      { firestoreField: 'longitude', postgresColumn: 'longitude', type: 'number', required: true },
      { firestoreField: 'timezone', postgresColumn: 'timezone', type: 'string', defaultValue: 'Asia/Riyadh' },
      { firestoreField: 'method', postgresColumn: 'method', type: 'number', defaultValue: 4 },
      { firestoreField: 'lastSyncedAt', postgresColumn: 'last_synced_at', type: 'timestamp' },
      { firestoreField: 'source', postgresColumn: 'source', type: 'string', defaultValue: 'aladhan' },
      { firestoreField: 'timingsByDate', postgresColumn: 'timings_by_date', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'adjustments', postgresColumn: 'adjustments', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  frontendConfigs: {
    firestoreCollection: 'frontendConfigs',
    postgresTable: 'frontend_configs',
    primaryKey: 'id',
    order: 31,
    description: 'تخصيص الواجهات والبانرات والإعلانات (Frontend Configs)',
    dependencies: [],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'type', postgresColumn: 'type', type: 'string', defaultValue: 'tenant' },
      { firestoreField: 'name', postgresColumn: 'name', type: 'string', required: true },
      { firestoreField: 'description', postgresColumn: 'description', type: 'string' },
      { firestoreField: 'logoUrl', postgresColumn: 'logo_url', type: 'string' },
      { firestoreField: 'contactEmail', postgresColumn: 'contact_email', type: 'string' },
      { firestoreField: 'contactPhone', postgresColumn: 'contact_phone', type: 'string' },
      { firestoreField: 'contactWhatsapp', postgresColumn: 'contact_whatsapp', type: 'string' },
      { firestoreField: 'address', postgresColumn: 'address', type: 'string' },
      { firestoreField: 'showSupervisor', postgresColumn: 'show_supervisor', type: 'boolean', defaultValue: true },
      { firestoreField: 'showPrayerTimes', postgresColumn: 'show_prayer_times', type: 'boolean', defaultValue: true },
      { firestoreField: 'primaryColor', postgresColumn: 'primary_color', type: 'string' },
      { firestoreField: 'banners', postgresColumn: 'banners', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'announcements', postgresColumn: 'announcements', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'sections', postgresColumn: 'sections', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'updatedAt', postgresColumn: 'updated_at', type: 'timestamp' },
    ],
  },

  audit_logs: {
    firestoreCollection: 'audit_logs',
    postgresTable: 'audit_logs',
    primaryKey: 'id',
    order: 32,
    description: 'سجلات الرقابة الأمنية (Audit Logs)',
    dependencies: [],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'userId', postgresColumn: 'user_id', type: 'string', required: true },
      { firestoreField: 'userName', postgresColumn: 'user_name', type: 'string', required: true },
      { firestoreField: 'userRole', postgresColumn: 'user_role', type: 'string', required: true },
      { firestoreField: 'action', postgresColumn: 'action', type: 'string', required: true },
      { firestoreField: 'entityType', postgresColumn: 'entity_type', type: 'string', required: true },
      { firestoreField: 'entityId', postgresColumn: 'entity_id', type: 'string', required: true },
      { firestoreField: 'entityName', postgresColumn: 'entity_name', type: 'string' },
      { firestoreField: 'previousValue', postgresColumn: 'previous_value', type: 'jsonb' },
      { firestoreField: 'newValue', postgresColumn: 'new_value', type: 'jsonb' },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'timestamp', postgresColumn: 'timestamp', type: 'timestamp', required: true },
    ],
  },

  report_logs: {
    firestoreCollection: 'report_logs',
    postgresTable: 'report_logs',
    primaryKey: 'id',
    order: 33,
    description: 'سجلات التقارير والرسائل المرسلة (Report Logs)',
    dependencies: [],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'recipientType', postgresColumn: 'recipient_type', type: 'string', required: true },
      { firestoreField: 'recipientName', postgresColumn: 'recipient_name', type: 'string', required: true },
      { firestoreField: 'recipientPhone', postgresColumn: 'recipient_phone', type: 'string' },
      { firestoreField: 'studentId', postgresColumn: 'student_id', type: 'string' },
      { firestoreField: 'teacherId', postgresColumn: 'teacher_id', type: 'string' },
      { firestoreField: 'reportType', postgresColumn: 'report_type', type: 'string', required: true },
      { firestoreField: 'title', postgresColumn: 'title', type: 'string', required: true },
      { firestoreField: 'content', postgresColumn: 'content', type: 'string', required: true },
      { firestoreField: 'timestamp', postgresColumn: 'timestamp', type: 'timestamp', required: true },
      { firestoreField: 'status', postgresColumn: 'status', type: 'string', defaultValue: 'sent' },
    ],
  },

  academic_archives: {
    firestoreCollection: 'academic_archives',
    postgresTable: 'academic_archives',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 34,
    description: 'أرشيف الفصول الدراسية المغلقة (Academic Archives)',
    dependencies: ['tenants'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'tenantName', postgresColumn: 'tenant_name', type: 'string', required: true },
      { firestoreField: 'academicYear', postgresColumn: 'academic_year', type: 'string', required: true },
      { firestoreField: 'termName', postgresColumn: 'term_name', type: 'string', required: true },
      { firestoreField: 'archivedAt', postgresColumn: 'archived_at', type: 'timestamp', required: true },
      { firestoreField: 'archivedBy', postgresColumn: 'archived_by', type: 'string', required: true },
      { firestoreField: 'totalStudents', postgresColumn: 'total_students', type: 'number', defaultValue: 0 },
      { firestoreField: 'totalHalaqahs', postgresColumn: 'total_halaqahs', type: 'number', defaultValue: 0 },
      { firestoreField: 'overallMasteryRate', postgresColumn: 'overall_mastery_rate', type: 'number', defaultValue: 0 },
      { firestoreField: 'notes', postgresColumn: 'notes', type: 'string' },
      { firestoreField: 'studentSnapshots', postgresColumn: 'student_snapshots', type: 'jsonb', defaultValue: [] },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
    ],
  },

  support_sessions: {
    firestoreCollection: 'support_sessions',
    postgresTable: 'support_sessions',
    primaryKey: 'id',
    tenantKey: 'tenant_id',
    order: 35,
    description: 'جلسات الدعم الفني الطارئ (Emergency Support Sessions)',
    dependencies: ['tenants'],
    fieldMappings: [
      { firestoreField: 'id', postgresColumn: 'id', type: 'string', required: true },
      { firestoreField: 'systemAdminUid', postgresColumn: 'system_admin_uid', type: 'string', required: true },
      { firestoreField: 'systemAdminName', postgresColumn: 'system_admin_name', type: 'string', required: true },
      { firestoreField: 'tenantId', postgresColumn: 'tenant_id', type: 'string', isForeignKey: true, foreignKeyTable: 'tenants' },
      { firestoreField: 'reason', postgresColumn: 'reason', type: 'string', required: true },
      { firestoreField: 'expiresAt', postgresColumn: 'expires_at', type: 'timestamp', required: true },
      { firestoreField: 'isActive', postgresColumn: 'is_active', type: 'boolean', defaultValue: true },
      { firestoreField: 'rolePermissionsOverrides', postgresColumn: 'role_permissions_overrides', type: 'jsonb', defaultValue: {} },
      { firestoreField: 'createdAt', postgresColumn: 'created_at', type: 'timestamp' },
    ],
  },
};
